# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='direction',
            field=models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], default='in', max_length=4),
        ),
    ]
