# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_entry_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='auto',
            field=models.BooleanField(default=False),
        ),
    ]
